// Stage P5 — audio. Replaces the inert CocosDenshion::SimpleAudioEngine stub that used to live in
// seam_link_stubs.mm (that section is deleted; keeping it would be a duplicate symbol).
//
// The engine's entire audio contract is the handful of calls below (docs/resources-and-audio.md),
// and it passes BARE FILENAMES ("explosion.caf", "Eden_title.mp3") with no directory — the iOS
// build resolved those against the app bundle, where every resource is flat. On the web the assets
// keep their media/ subdirectory layout, so a build-time manifest (public/audio-manifest.json,
// generated by CMakeLists.txt) maps basename -> relative path. See CMakeLists.txt for why the
// audio is served over HTTP instead of being --preload-file'd: it is ~45 MB, which would more than
// double the initial download, and none of it is needed before the first sound plays.
//
// Two different playback paths, on purpose:
//   * EFFECTS are short and need low latency and overlap (several explosions at once), so they go
//     through Web Audio as decoded AudioBuffers, cached by name after first fetch.
//   * MUSIC is minutes long, so it streams through an <audio> element. Decoding a whole track into
//     an AudioBuffer would mean holding tens of MB of PCM and a long stall before the first note.
//
// The .caf effects are decoded BY HAND rather than via decodeAudioData. They are Core Audio Format
// containers holding linear PCM ('lpcm', 16-bit 44.1 kHz), which Chrome's decodeAudioData does not
// accept — but an LPCM CAF is just a chunk header followed by raw samples, so parsing it is a few
// lines and costs no build-time transcode step and no ffmpeg dependency. (.wav and .mp3 still go
// through decodeAudioData/<audio>, which handle them natively.)

#include "../../../Classes/SimpleAudioEngine.h"

#include <emscripten.h>

// ---------------------------------------------------------------------------------------------
// JS side: manifest lookup, CAF decode, effect cache, music element.
// ---------------------------------------------------------------------------------------------
EM_JS(void, eden_audio_js_init, (), {
    if (Module.__edenAudio) return;
    var A = {
        ctx: null,
        manifest: null,
        manifestPending: null,
        buffers: {},      // name -> AudioBuffer (or null once known-bad)
        pending: {},      // name -> Promise
        voices: {},       // id -> AudioBufferSourceNode
        nextId: 1,
        music: null,
        musicName: null,
        musicVolume: 1.0,
        // Browsers start an AudioContext suspended until a user gesture; the engine happily calls
        // playEffect before the player has clicked anything, so resume lazily on every gesture and
        // let pre-gesture sounds drop rather than queueing a burst that all fires at once later.
        resume: function() {
            if (A.ctx && A.ctx.state === 'suspended') A.ctx.resume();
            if (A.music && A.music.paused && A.musicWanted) A.music.play().catch(function(){});
        }
    };

    A.effectsVolume = 1.0;

    A.getCtx = function() {
        if (!A.ctx) {
            // `window` doesn't exist under the headless `node eden.js` drive (see PORT-STATUS.md
            // "Headless driving") — World::World() -> Resources() -> SimpleAudioEngine::sharedEngine()
            // runs this unconditionally at startup, so a bare `window.AudioContext` reference here
            // threw ReferenceError on every headless run, not just ones that touch audio.
            var C = (typeof window !== 'undefined') && (window.AudioContext || window.webkitAudioContext);
            if (C) {
                A.ctx = new C();
                // All effect voices route through this single gain node so setEffectsVolume can
                // scale every currently-playing (and future) effect at once, rather than having to
                // reach into each individual BufferSourceNode. Music is unaffected — it has its own
                // <audio>.volume path (eden_audio_set_music_volume) per the two-path design above.
                A.effectsGain = A.ctx.createGain();
                A.effectsGain.gain.value = A.effectsVolume;
                A.effectsGain.connect(A.ctx.destination);
            }
        }
        return A.ctx;
    };

    A.loadManifest = function() {
        if (A.manifest) return Promise.resolve(A.manifest);
        if (!A.manifestPending) {
            A.manifestPending = fetch('audio-manifest.json')
                .then(function(r) { return r.ok ? r.json() : {}; })
                .catch(function() { return {}; })
                .then(function(m) { A.manifest = m; return m; });
        }
        return A.manifestPending;
    };

    A.urlFor = function(name) {
        var rel = A.manifest && A.manifest[name];
        return rel ? ('audio/' + rel) : null;
    };

    // Core Audio Format, linear-PCM only. Layout: "caff" + version/flags (4 bytes), then chunks of
    // { 4-byte type, 8-byte big-endian size, payload }. We need 'desc' (the format) and 'data'
    // (whose payload starts with a 4-byte edit-count that is NOT sample data).
    A.decodeCaf = function(arrayBuf) {
        var dv = new DataView(arrayBuf);
        if (dv.getUint32(0, false) !== 0x63616666) return null;  // 'caff'
        var off = 8, fmt = null, data = null;
        while (off + 12 <= dv.byteLength) {
            var type = dv.getUint32(off, false);
            // Chunk sizes are int64 BE; audio chunks are far below 2^32 so the low word is enough.
            var size = dv.getUint32(off + 8, false);
            var body = off + 12;
            if (type === 0x64657363) {  // 'desc'
                // CAFAudioFormat field order: mSampleRate(f64), mFormatID, mFormatFlags,
                // mBytesPerPacket, mFramesPerPacket, mChannelsPerFrame, mBitsPerChannel.
                fmt = {
                    sampleRate: dv.getFloat64(body, false),
                    formatID: dv.getUint32(body + 8, false),
                    formatFlags: dv.getUint32(body + 12, false),
                    channels: dv.getUint32(body + 24, false),
                    bitsPerChannel: dv.getUint32(body + 28, false)
                };
            } else if (type === 0x64617461) {  // 'data'
                data = { start: body + 4, length: (size === 0xffffffff ? dv.byteLength - body - 4 : size - 4) };
            }
            if (size === 0xffffffff) break;  // unspecified size => runs to EOF
            off = body + size;
        }
        if (!fmt || !data) return null;
        if (fmt.formatID === 0x696d6134) return A.decodeIma4(dv, fmt, data);  // 'ima4'
        if (fmt.formatID !== 0x6c70636d) return null;                         // else 'lpcm' only
        if (fmt.bitsPerChannel !== 16) return null;

        var little = (fmt.formatFlags & 2) !== 0;  // kCAFLinearPCMFormatFlagIsLittleEndian
        var frames = Math.floor(data.length / (2 * fmt.channels));
        var ctx = A.getCtx();
        if (!ctx || frames <= 0) return null;
        var buf = ctx.createBuffer(fmt.channels, frames, fmt.sampleRate);
        for (var ch = 0; ch < fmt.channels; ch++) {
            var out = buf.getChannelData(ch);
            var p = data.start + ch * 2;
            var stride = 2 * fmt.channels;
            for (var i = 0; i < frames; i++, p += stride) out[i] = dv.getInt16(p, little) / 32768;
        }
        return buf;
    };

    // Apple IMA4 (4-bit IMA/ADPCM) — 428 of the 436 .caf effects use it; only 8 are raw lpcm.
    // Each packet is 34 bytes per channel and yields 64 frames: a 2-byte big-endian preamble
    // (top 9 bits = initial predictor, low 7 bits = step index) followed by 32 bytes of nibbles,
    // low nibble first. Multi-channel files interleave whole packets, one per channel.
    A.IMA_INDEX = [-1,-1,-1,-1,2,4,6,8,-1,-1,-1,-1,2,4,6,8];
    A.IMA_STEP = [7,8,9,10,11,12,13,14,16,17,19,21,23,25,28,31,34,37,41,45,50,55,60,66,73,80,88,
                  97,107,118,130,143,157,173,190,209,230,253,279,307,337,371,408,449,494,544,598,
                  658,724,796,876,963,1060,1166,1282,1411,1552,1707,1878,2066,2272,2499,2749,3024,
                  3327,3660,4026,4428,4871,5358,5894,6484,7132,7845,8630,9493,10442,11487,12635,
                  13899,15289,16818,18500,20350,22385,24623,27086,29794,32767];
    A.decodeIma4 = function(dv, fmt, data) {
        var ctx = A.getCtx(); if (!ctx) return null;
        var ch = fmt.channels || 1;
        var packetsTotal = Math.floor(data.length / 34);
        var packetsPerCh = Math.floor(packetsTotal / ch);
        var frames = packetsPerCh * 64;
        if (frames <= 0) return null;
        var buf = ctx.createBuffer(ch, frames, fmt.sampleRate);
        for (var c = 0; c < ch; c++) {
            var out = buf.getChannelData(c);
            var o = 0;
            for (var pk = 0; pk < packetsPerCh; pk++) {
                var p = data.start + (pk * ch + c) * 34;
                var pre = dv.getUint16(p, false);
                var pred = pre & 0xFF80;
                if (pred & 0x8000) pred -= 0x10000;   // sign-extend the 16-bit predictor
                var idx = pre & 0x7F;
                if (idx > 88) idx = 88;
                for (var b = 0; b < 32; b++) {
                    var byte = dv.getUint8(p + 2 + b);
                    for (var half = 0; half < 2; half++) {
                        var nib = half ? (byte >> 4) & 0x0F : byte & 0x0F;
                        var step = A.IMA_STEP[idx];
                        var diff = step >> 3;
                        if (nib & 1) diff += step >> 2;
                        if (nib & 2) diff += step >> 1;
                        if (nib & 4) diff += step;
                        if (nib & 8) diff = -diff;
                        pred += diff;
                        if (pred > 32767) pred = 32767; else if (pred < -32768) pred = -32768;
                        idx += A.IMA_INDEX[nib];
                        if (idx < 0) idx = 0; else if (idx > 88) idx = 88;
                        out[o++] = pred / 32768;
                    }
                }
            }
        }
        return buf;
    };

    A.fetchEffect = function(name) {
        if (name in A.buffers) return Promise.resolve(A.buffers[name]);
        if (A.pending[name]) return A.pending[name];
        A.pending[name] = A.loadManifest().then(function() {
            var url = A.urlFor(name);
            if (!url) { A.buffers[name] = null; return null; }
            return fetch(url).then(function(r) {
                if (!r.ok) throw new Error('http ' + r.status);
                return r.arrayBuffer();
            }).then(function(ab) {
                if (/\.caf$/i.test(name)) return A.decodeCaf(ab);
                var ctx = A.getCtx();
                if (!ctx) return null;
                return ctx.decodeAudioData(ab);
            }).then(function(buf) {
                A.buffers[name] = buf || null;
                return A.buffers[name];
            }).catch(function() { A.buffers[name] = null; return null; });
        });
        return A.pending[name];
    };

    // Create the context up front rather than lazily on the first effect. Chrome only honours
    // resume() from inside a user-gesture handler, so a context that does not exist yet when the
    // player's first click arrives stays suspended until they happen to click again — which reads
    // as "audio is just broken". Creating it here means the very first gesture unblocks it.
    A.getCtx();
    if (typeof window !== 'undefined') {
        ['pointerdown', 'mousedown', 'keydown', 'touchstart'].forEach(function(ev) {
            window.addEventListener(ev, A.resume, { capture: true });
        });
    }

    Module.__edenAudio = A;
});

EM_JS(unsigned int, eden_audio_play_effect, (const char *name, int loop), {
    var A = Module.__edenAudio; if (!A) return 0;
    var n = UTF8ToString(name); if (!n) return 0;
    var ctx = A.getCtx(); if (!ctx) return 0;
    A.resume();
    var id = A.nextId++;
    // Async by nature (first play of a sound has to fetch it). Returning the id immediately keeps
    // the engine's synchronous contract; a stopEffect(id) arriving before the fetch lands is
    // handled by checking that the id is still registered when the buffer is ready.
    A.voices[id] = null;
    A.fetchEffect(n).then(function(buf) {
        if (!buf || !(id in A.voices)) return;
        var src = ctx.createBufferSource();
        src.buffer = buf;
        src.loop = !!loop;
        src.connect(A.effectsGain || ctx.destination);
        src.onended = function() { delete A.voices[id]; };
        src.start(0);
        A.voices[id] = src;
    });
    return id;
});

EM_JS(void, eden_audio_stop_effect, (unsigned int id), {
    var A = Module.__edenAudio; if (!A) return;
    var src = A.voices[id];
    if (src) { try { src.stop(0); } catch (e) {} }
    delete A.voices[id];
});

EM_JS(void, eden_audio_preload, (const char *name), {
    var A = Module.__edenAudio; if (!A) return;
    var n = UTF8ToString(name); if (n) A.fetchEffect(n);
});

EM_JS(void, eden_audio_unload, (const char *name), {
    var A = Module.__edenAudio; if (!A) return;
    var n = UTF8ToString(name);
    if (n) { delete A.buffers[n]; delete A.pending[n]; }
});

EM_JS(void, eden_audio_play_music, (const char *name, int loop), {
    var A = Module.__edenAudio; if (!A) return;
    var n = UTF8ToString(name); if (!n) return;
    A.loadManifest().then(function() {
        var url = A.urlFor(n);
        if (!url) return;
        if (A.music && A.musicName === n) { A.music.loop = !!loop; A.musicWanted = true;
            A.music.play().catch(function(){}); return; }
        if (A.music) { A.music.pause(); A.music.src = ''; }
        A.music = new Audio(url);
        A.music.loop = !!loop;
        A.music.volume = A.musicVolume;
        A.musicName = n;
        A.musicWanted = true;
        A.music.play().catch(function() {});  // blocked until a gesture; A.resume retries
    });
});

EM_JS(void, eden_audio_stop_music, (), {
    var A = Module.__edenAudio; if (!A || !A.music) return;
    A.musicWanted = false;
    A.music.pause();
    A.music.currentTime = 0;
});

EM_JS(int, eden_audio_is_music_playing, (), {
    var A = Module.__edenAudio;
    return (A && A.music && !A.music.paused && !A.music.ended) ? 1 : 0;
});

EM_JS(void, eden_audio_set_music_volume, (float v), {
    var A = Module.__edenAudio; if (!A) return;
    A.musicVolume = Math.max(0, Math.min(1, v));
    if (A.music) A.music.volume = A.musicVolume;
});

EM_JS(float, eden_audio_get_music_volume, (), {
    var A = Module.__edenAudio;
    return A ? A.musicVolume : 0;
});

EM_JS(void, eden_audio_set_effects_volume, (float v), {
    var A = Module.__edenAudio; if (!A) return;
    A.effectsVolume = Math.max(0, Math.min(1, v));
    if (A.effectsGain) A.effectsGain.gain.value = A.effectsVolume;
});

EM_JS(float, eden_audio_get_effects_volume, (), {
    var A = Module.__edenAudio;
    return A ? A.effectsVolume : 0;
});

// ---------------------------------------------------------------------------------------------
// The façade the engine actually calls.
// ---------------------------------------------------------------------------------------------
namespace CocosDenshion {

static SimpleAudioEngine *g_sharedEngine = 0;

SimpleAudioEngine::SimpleAudioEngine() {}
SimpleAudioEngine::~SimpleAudioEngine() {}

// Returns a real singleton rather than null, because callers immediately message the result
// without checking (unchanged from the stub this replaces).
SimpleAudioEngine *SimpleAudioEngine::sharedEngine() {
    if (!g_sharedEngine) {
        eden_audio_js_init();
        g_sharedEngine = new SimpleAudioEngine();
    }
    return g_sharedEngine;
}

unsigned int SimpleAudioEngine::playEffect(const char *filePath, bool loop) {
    if (!filePath) return 0;
    return eden_audio_play_effect(filePath, loop ? 1 : 0);
}
void SimpleAudioEngine::stopEffect(unsigned int soundId) { eden_audio_stop_effect(soundId); }
void SimpleAudioEngine::preloadEffect(const char *filePath) {
    if (filePath) eden_audio_preload(filePath);
}
void SimpleAudioEngine::unloadEffect(const char *filePath) {
    if (filePath) eden_audio_unload(filePath);
}
void SimpleAudioEngine::playBackgroundMusic(const char *filePath, bool loop) {
    if (filePath) eden_audio_play_music(filePath, loop ? 1 : 0);
}
void SimpleAudioEngine::stopBackgroundMusic(bool releaseData) {
    (void)releaseData;
    eden_audio_stop_music();
}
bool SimpleAudioEngine::isBackgroundMusicPlaying() { return eden_audio_is_music_playing() != 0; }
float SimpleAudioEngine::getBackgroundMusicVolume() { return eden_audio_get_music_volume(); }
void SimpleAudioEngine::setBackgroundMusicVolume(float volume) { eden_audio_set_music_volume(volume); }
float SimpleAudioEngine::getEffectsVolume() { return eden_audio_get_effects_volume(); }
void SimpleAudioEngine::setEffectsVolume(float volume) { eden_audio_set_effects_volume(volume); }

}  // namespace CocosDenshion
